### ISSUE TITLE
latest release of qch-book is an empty archive

### ISSUE THREAD

**Issue by marehr** [PeterFeicht/cppreference-doc#13]
See release page: https://github.com/PeterFeicht/cppreference-doc/releases/tag/v20190110

qch-book-20190110.tar.xz | 108 Bytes

**Comment by PeterFeicht** [comment]
Apparently this was caused by an update to `qhelpgenerator`, which now expects the input file to have a `.qhp` extension instead of `.xml`. I've updated the release with the proper QCH files, the next release will include the fix to the Makefile as well.
