### ISSUE TITLE
Update cppreference-doxygen-web.tag.xml

### ISSUE THREAD

**Issue by marehr** [PeterFeicht/cppreference-doc#14]
Hello @PeterFeicht,

thank you for your recent update. Could you also update `cppreference-doxygen-web.tag.xml`, because it is missing some of the c++20 keywords that are in the html archive.

Best regards,
marcel

/cc: @h-2

**Comment by mosra** [comment]
Not sure if this is the right place to comment, but would it be possible to also update the link at https://en.cppreference.com/w/File:cppreference-doxygen-web.tag.xml? The file referenced there is a very old version from 2014, not having anything from C++14, even. I used to build up-to-date versions manually using `make doc_doxygen` and only today I discovered there are up-to-date versions hidden in the `html-book-*.tar.xz` archives :)

**Comment by PeterFeicht** [comment]
@mosra I'll update it with the next release. The URL has changed in the meantime, the new URL is https://upload.cppreference.com/w/File:cppreference-doxygen-web.tag.xml

**Comment by marehr** [comment]
@PeterFeicht That means you made a new release?

**Comment by PeterFeicht** [comment]
Not yet, I'll close it when the new release is out, should be today or tomorrow.

**Comment by marehr** [comment]
Very polite ping :)

**Comment by PeterFeicht** [comment]
Just released [v20190602](https://github.com/PeterFeicht/cppreference-doc/releases/tag/v20190602). I wasn't able to update the tag file hosted on cppreference.com yet, but it's included in the HTML book as always.

**Comment by marehr** [comment]
You're the best :+1:
