### ISSUE TITLE
QCH fonts are too large

### ISSUE THREAD

**Issue by 10110111** [PeterFeicht/cppreference-doc#17]
When compared to the Qt documentation, cppreference appears to have really large fonts. And the problem is exacerbated with current Qt5 versions which lack QtWebKit, so one can't even scale down the main text: only the caption scales.

The fonts appear correct in the official QCH book release 20170409, and are already too large in the 20181028 release. And this problem remains with the releases made from this repo.

See the following screenshots for comparison between Qt docs and C++ docs.

`QString` docs @ Qt5 Assistant:
![QString @ Qt5 Assistant](https://user-images.githubusercontent.com/6376882/57248213-81422f80-704a-11e9-9540-fc541575588c.png)

`std::string` docs @ Qt5 Assistant:
![std::string docs @ Qt5 Assistant](https://user-images.githubusercontent.com/6376882/57248249-97e88680-704a-11e9-93c4-5d7f3afe4c8d.png)

Even if I open in Qt4 Assistant built with QtWebKit support, the fonts are too large, although the content is easier to scale (and formatting is less broken).

`std::string` docs @ Qt5 Assistant:
![std::string docs @ Qt5 Assistant](https://user-images.githubusercontent.com/6376882/57248360-d8480480-704a-11e9-8f96-9bbe5fb2a1ca.png)

**Comment by PeterFeicht** [comment]
This is something you should report upstream, it probably has to do with the CSS inlining during preprocessing.
I don't use the QCH book myself so I'm unlikely to invest much work in it. If you want to do a PR yourself I'll forward that upstream.

**Comment by 10110111** [comment]
Sorry, didn't realize this repo is a fork. I've reported it upstream: https://github.com/p12tic/cppreference-doc/issues/79.

**Comment by PeterFeicht** [comment]
I suppose I can close this, I'll pull in future upstream changes with a subsequent release anyway.
