### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by marehr** [PeterFeicht/cppreference-doc#20]
Hi Peter,

could you do a new release?

C++20 is right around the corner and the wiki changed quite substantial since the last release.

Please don't forget to update cppreference-doxygen-web.tag.xml.

**Comment by PeterFeicht** [comment]
I'll try to do a release in the next few days.

About the tag file: if you're talking about the one on cppreference.com, I tried to update that several times but failed. I asked on the Cpplang Slack about it but didn't get a response.

**Comment by marehr** [comment]
Thank you, Peter!

No I mean the one contained in your html-book-20200222.tar.xz release.

**Comment by PeterFeicht** [comment]
Well, that took some time. I should really try and do releases more often again...

I didn't update the indexes though, I'll see if I can get around to that until the next release.
