### ISSUE TITLE
Missing names

### ISSUE THREAD

**Issue by h-2** [PeterFeicht/cppreference-doc#28]
Thanks for your work on this first of all!

Even the latest release seems to be missing lots of C++20 stuff, like Concepts and things from `std::ranges::`. Is this a known issue?

**Comment by PeterFeicht** [comment]
Do you mean pages for things in C++20? This is just an offline clone of cppreference.com, so if a page is not on cppreference.com then it won't be here either.

If you're referring to Doxygen tag files, that content gets updated [upstream](https://github.com/p12tic/cppreference-doc) and recent changes will be included with every new release.

**Comment by h-2** [comment]
> Do you mean pages for things in C++20? This is just an offline clone of cppreference.com, so if a page is not on cppreference.com then it won't be here either.

No, I mean things like:
https://en.cppreference.com/w/cpp/concepts/integral
https://en.cppreference.com/w/cpp/ranges/filter_view

> If you're referring to Doxygen tag files, that content gets updated [upstream](https://github.com/p12tic/cppreference-doc) and recent changes will be included with every new release.

Ok, so I should report missing names upstream?

**Comment by PeterFeicht** [comment]
So you're talking about tag files?
Yes, please report missing entries upstream (or better yet, contribute them yourself).

**Comment by h-2** [comment]
> So you're talking about tag files?

Yep, I meant Doxygen tag files.

Just, so that there is no confusion: 
* if something is missing on the website, I will report at https://github.com/p12tic/cppreference-doc
* if something is on the website, but missing from the doxygen tag file, I will report it here and/or make a PR here

correct?

**Comment by PeterFeicht** [comment]
If something is missing from cppreference.com then you can contribute it yourself, there's nowhere to report that (it's a wiki after all).

In general: usually you'll want to report any issues with the offline archive at [p12tic/cppreference-doc](https://github.com/p12tic/cppreference-doc). Anything that's specific to this fork you can report here of course.

Specifically Doxygen tag files: you can try and open a ticket upstream, but you might wanna contribute missing entries yourself and open a PR instead ;-)

**Comment by h-2** [comment]
> If something is missing from cppreference.com then you can contribute it yourself, there's nowhere to report that (it's a wiki after all).

It's not about things missing from the Wiki. I already said before that I mean things like the following:
https://en.cppreference.com/w/cpp/concepts/integral
https://en.cppreference.com/w/cpp/ranges/filter_view

> In general: usually you'll want to report any issues with the offline archive at [p12tic/cppreference-doc](https://github.com/p12tic/cppreference-doc). 

I opened an issue there but got no response so far: https://github.com/p12tic/cppreference-doc/issues/127

> Anything that's specific to this fork you can report here of course.

I am not sure what is specific to this port. I inherited a workflow that pulls cppreference-doxygen-web.tag.xml from the html-book from this fork. Is that specific to this port? I could not find these files in the parent repo.

> Specifically Doxygen tag files: you can try and open a ticket upstream, but you might wanna contribute missing entries yourself and open a PR instead ;-)

I would be very willing to add things, but I have no clue where/how.
