### ISSUE TITLE
`std::experimental::erase` treated as namespaces in doxygen tagfile

### ISSUE THREAD

**Issue by marzer** [PeterFeicht/cppreference-doc#29]
Hello,

In the most recent release the doxygen web tagfile has some weird namespaces that include `(` characters. Looks like this might be the result of typo in a config change somewhere causing `std::experimental::erase` to be treated as a namespace instead of a function, but I don't know enough about how this project works to dive into it myself. 

The first example in question appears in `cppreference-doxygen-web.tag.xml` at line 30706:

```xml
  <compound kind="namespace">
    <name>std::experimental::erase(std</name> <!-- this line -->
    <filename></filename>
    <member kind="function">
```

You'll be able to quickly find others just by skipping through the search results for `kind="namespace"`, since there aren't too many.

**Comment by PeterFeicht** [comment]
I'm not using the tag files myself, but I'll see if I can figure anything out.
