### ISSUE TITLE
Provide cppreference-doxygen-web.tag.xml

### ISSUE THREAD

**Issue by marehr** [PeterFeicht/cppreference-doc#3]
Hi PeterFeicht,

could you also provide the`http://en.cppreference.com/w/File:cppreference-doxygen-web.tag.xml` file?
That would be awesome!

Thank you!

**Comment by PeterFeicht** [comment]
Added to the current release and will be included with the HTML book in future releases.

**Comment by marehr** [comment]
Thank you!
