### ISSUE TITLE
See also links between C and C++ documentation are removed

### ISSUE THREAD

**Issue by SainoNamkho** [PeterFeicht/cppreference-doc#30]
Could you provide unprocessed archives in the release page since `make source` is rather slow because connection to cppreference site is slow in my region, and I need to process the archive myself.
What I need indeed is html book made without `preprocess.remove_see_also`, but it seems improper to ask you to make this version for me. So it will be appreciated if you can provide the source archive and let me process it on demand.

**Comment by PeterFeicht** [comment]
The release already contains an archive with unprocessed sources. `cppreference-doc-<version>` has the unprocessed HTML in the `reference` directory, as well as all the necessary scripts for building a release yourself.

I actually don't know what exactly `remove_see_also` removes, could you give me an example of a page that it modifies?

**Comment by PeterFeicht** [comment]
Actually I just realized that this got in by mistake. When I started this fork, one of the first things I did was to remove that preprocessing step. It must have slipped through back in when preprocessing was converted from XSLT to Python.

I'll fix that, those links will be part of the next release again.

**Comment by SainoNamkho** [comment]
After `remove_see_also `:
![image](https://user-images.githubusercontent.com/23036788/185635938-6551ce04-3087-4607-9ec2-4ad96b3c04a4.png)

Raw version of https://en.cppreference.com/w/cpp/language/sizeof
![image](https://user-images.githubusercontent.com/23036788/185636077-7992f83a-b5df-4e4f-8ace-36e430add8dc.png)

The major difference is link to C documentation is removed, maybe also some other link I've not realized.
