### ISSUE TITLE
text unreadable with latest Qt Assitant 5.15.7

### ISSUE THREAD

**Issue by Waqar144** [PeterFeicht/cppreference-doc#33]
Seems like it is not able to set the correct foreground color for text if its unspecified?

![image](https://user-images.githubusercontent.com/7696024/202429327-14fb640d-7a6e-4531-8375-3e6d5a879241.png)

**Comment by Waqar144** [comment]
The problem is related to dark theme. The new renderer uses white color for the foreground text which makes things unreadable. For now I am using the following workaround:

```
export QT_QPA_PLATFORMTHEME=gtk3 # set env var
assitant
```

**Comment by PeterFeicht** [comment]
I think this needs support for dark mode to be added to the site's style, which doesn't seem to support dark mode at all. Nothing that can be fixed on my end.
