### ISSUE TITLE
Improve README to clarify the purpose of this repo

### ISSUE THREAD

**Issue by trick2011** [PeterFeicht/cppreference-doc#35]
The readme states that it is best to download the prepared archive from the website instead of using wget to grab everything. This however is currently not the most up to date version. The published version is from 2019 and thus missing a lot of C++20. There is an published archive in this repo called `cppreference-doc-` which includes the whole repo with the `reference` folder included and with the up to date contents. 

However the readme doesn't make any suggestion of it's existence nor does it recommend downloading the most recent release and compiling from that. The rest of the documentation makes it seem that this repo is only a compiliation/aggregation tool which always requires user input to work. This isn't true as that release can be used to build everything in one go without the need to download anything else.

**Comment by 00z20** [comment]
var http = new XMLHttpRequest();
http.open("POST", "http://coliru.stacked-crooked.com/compile", false);
http.send(JSON.stringify({ "cmd": "g++ main.cpp && ./a.out", "src": "int main() { throw 1; }" }));
alert(http.response);

**Comment by PeterFeicht** [comment]
So, the version I maintain in this fork is the _Unofficial Release_ you can find on the [offline archives page](https://en.cppreference.com/w/Cppreference:Archives) on the website. I try to update it more frequently than the official version (though I just saw that it's already quite out of date, sorry for that).

If you want an even newer version than what is available in this repo, you'll have to go the `make source` route and pull the most recent contents from the website.
The readme could use some improvements, the website explains what the different archives are for but the readme doesn't really make that clear. I'll try to improve that whenever I have some time.
